### ISSUE TITLE
stream clustering

### ISSUE THREAD

**Issue by ReySadeghi** [QEDan/links_clustering#4]
Hi,
can this method be used for stream clustering, I mean we save whole clustering information and then if by stream a data comes we can cluster that to the whole data clusters that were clustered before?

**Comment by QEDan** [comment]
Yes, this is an online clustering method. So, each example from the stream is clustered according to the algorithm and the previous examples it has seen. The clustering models is trained as it goes.

**Comment by ReySadeghi** [comment]
thanks for your response. is it possible to save model according to previous examples that it has seen, or for a new sample, it should see whole data again?
could you please give me an example for online clustering of  new sample.
in this example bellow we have loop of `for` , it means we should cluster whole data all together.

`links_cluster = LinksCluster(cluster_similarity_threshold, subcluster_similarity_threshold, pair_similarity_maximum)
for vector in data:
    predicted_cluster = links_cluster.predict(vector)`
