### ISSUE TITLE
What is the time complexity? What is the space complexity?

### ISSUE THREAD

**Issue by zhangyu13141** [QEDan/links_clustering#6]

**Comment by zhangyu13141** [comment]
how to set this three threshold?

**Comment by zhangyu13141** [comment]
what is the disadvantages of this algorithm?

**Comment by QEDan** [comment]
The time and space complexity is an interesting question. It doesn't appear to be discussed in the paper. I implemented this in a single sitting three years ago and I don't really remember how the algorithm works. If you do an analysis, please let us know.

Setting the thresholds is problem-dependent. So, you need to understand your data and/or find an evaluation metric that you can use to tune them.

The main disadvantage of this algorithm is that it is an online algorithm, and offline algorithms tend to do a much better job. But, in some real-time applications, offline clustering is not an option. The authors of this method discuss some of the challenges of clustering in their paper on speaker diarization: https://arxiv.org/abs/1710.10468
